name: Tekton Base

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch: {}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: tektoncd/pipeline

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Docker login
        run: |
          docker login -u mattmoor -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base
        run: |
          # Could be: ${{ steps.buildx.outputs.platforms }}
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
            --file ./images/Dockerfile --tag docker.io/mattmoor/tekton-base:latest --push .

      - name: Post failure notice to Slack
        uses: rtCamp/action-slack-notify@v2.1.0
        if: ${{ failure() }}
        env:
          SLACK_ICON: http://github.com/${{ matrix.org }}.png?size=48
          SLACK_USERNAME: sockpuppet
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

          SLACK_CHANNEL: 'mink'
          SLACK_COLOR: '#8E1600'
          MSG_MINIMAL: 'true'
          SLACK_TITLE: Daily Tekton base buildx failed.
          SLACK_MESSAGE: |
            For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
